---

title: "inconsistent shared object state after unlocked object exception"
layout: issue
tags: 
permalink: /browse/CDV-822

issue_key: CDV-822
issue_numeric_sort_key: 822
issuetype: "Bug"
project: "Community Development (Terracotta Server)"
project_key: "CDV"
status: "Open"
resolution: ""
priority: "2 Major"
components: "DSO:L1"
labels: 
assignee: "interfaces"
reporter: "wharley"
votes:  0
watchers: 1

created: "2008-07-31T20:14:12.000-0400"
updated: "2011-12-16T18:37:11.000-0500"
resolved: ""

attachments:
- filename: "Archive.zip"
  author: "wharley"
  size: 2.00 k
  mimeType: application/x-zip-compressed




---

{% raw %}

## Description

<div markdown="1" class="description">

Attempting to mutate a field of a shared object without an autolock will cause an UnlockedSharedObjectException to be thrown.  After this exception, the value of the field will be null for all other viewers for which the field was previously unresolved.

The following code snippet demonstrates the problem (see attached archive for complete test code):

  public void run() \{
    root = new A();
    try {
      // attempt to mutate without a shared lock
      root.o = new Object();
    } catch (Throwable t) {
      // ignore unlocked object exception
    }
    Assert.assertNotNull(root.o);
  \}

In this snippet, the assertion will fail for all L1 clients for which the field was unresolved, i.e., all but the first.

The reason for the bug is that in TCObjectImpl.objectFieldChanged, we call clearReference() before calling ClientTransactionManager.fieldChanged().  If fieldChanged() throws an exception, the reference has still been cleared, even though the field was not actually set.  If the field was previously unresolved, it will now contain a null but there will be no reference; this condition is identical to a "real" null.

NOTE: The same problem exists for a similar pattern on arrays (and the test should be updated to cover this). 

</div>

## Comments



{% endraw %}
