---

title: "Figure out why modifying a shared object from on-load didn't give an exception"
layout: issue
tags: 
permalink: /browse/CDV-1442

issue_key: CDV-1442
issue_numeric_sort_key: 1442
issuetype: "Bug"
project: "Community Development (Terracotta Server)"
project_key: "CDV"
status: "Resolved"
resolution: "Won't Fix"
priority: "2 Major"
components: ""
labels: 
assignee: "interfaces"
reporter: "stulscot"
votes:  0
watchers: 3

created: "2009-12-21T06:52:03.000-0500"
updated: "2014-02-12T20:44:42.000-0500"
resolved: "2014-02-12T20:44:42.000-0500"

---



{% raw %}


## Attachments
  
* <em>stulscot</em> (839.000, text/x-java-source) [OnLoadTest.java](/attachments/CDV/CDV-1442/OnLoadTest.java)
  
* <em>stulscot</em> (1.000 k, text/xml) [tc-config.xml](/attachments/CDV/CDV-1442/tc-config.xml)
  



## Description

<div markdown="1" class="description">

Any modifications made to distributed objects don't seem to be propagated during the on-load initialisation.

In the attached example each node adds its DsoNode to a HashSet in the method configured in the <on-load> element in tc-config.xml. On the first node this is run on "nodes = [ClientID[0]]" is always output even after a second node is started. The second node always outputs "nodes = [ClientID[0], ClientID[1]]".

If line 40 of OnLoadTest.java is uncommented and the <on-load> section is commented out in tc-config.xml the example works as excepted.

If this is the correct behaviour then it should be clearly stated in the documentation that code called to initialise the object when faulted in should not modify distributed objects in any way.

The example can be compiled with 'javac -cp terracotta-api-1.1.0.jar OnLoadTest.java'.

</div>

## Comments


{:.comment-heading}
### **Steve Harris** <span class="date">2009-12-21</span>

<div markdown="1" class="comment">

That's intentionally. On-load is designed for updating transient and or local state.

</div>


{:.comment-heading}
### **Stuart Scott** <span class="date">2010-01-06</span>

<div markdown="1" class="comment">

Since meaningful exceptions are thrown when a shared object is modified without holding a lock, would it not be appropriate in this case to also throw an exception? The current behaviour silently modifies the local instance of the shared object while not propagating changes. Also the documentation regarding this behaviour is rather vague.

</div>


{:.comment-heading}
### **Steve Harris** <span class="date">2010-01-06</span>

<div markdown="1" class="comment">

Yeah, I'm kinda suprised it doesn't. We'll have to take a look

</div>


{:.comment-heading}
### **Hung Huynh** <span class="date">2014-02-12</span>

<div markdown="1" class="comment">

DSO is discontinued

</div>



{% endraw %}
