---

title: "exceptions throw in an <on-load> method are swallowed"
layout: issue
tags: 
permalink: /browse/CDV-531

issue_key: CDV-531
issue_numeric_sort_key: 531
issuetype: "Bug"
project: "Community Development (Terracotta Server)"
project_key: "CDV"
status: "Resolved"
resolution: "Won't Fix"
priority: "2 Major"
components: "DSO:L1"
labels: 
assignee: "teck"
reporter: "teck"
votes:  0
watchers: 0

created: "2007-12-03T15:49:04.000-0500"
updated: "2013-09-06T16:18:56.000-0400"
resolved: "2013-09-06T16:18:56.000-0400"

---



{% raw %}



## Description

<div markdown="1" class="description">

origin: http://forums.terracotta.org/forums/posts/list/658.page

If you throw an exception from an on-load method, the actual exception gets swallowed. There is a error statement that goes both the console and the terracotta log file, but the wrong beanshell method is getting called. 

To reproduce this, just write an on-load method that throws an exception. I don't think there is any way to find out what the actual exception was




</div>

## Comments



{% endraw %}
