---

title: "EhcacheXAResourceImpl.recover() incorrectly marks recovered contexts as rollback only"
layout: issue
tags: 
permalink: /browse/EHC-670

issue_key: EHC-670
issue_numeric_sort_key: 670
issuetype: "Bug"
project: "Ehcache Core"
project_key: "EHC"
status: "Closed"
resolution: "Fixed"
priority: "2 Major"
components: "ehcache-core"
labels: 
assignee: "hsingh"
reporter: "lorban"
votes:  0
watchers: 0

created: "2010-04-01T03:17:45.000-0400"
updated: "2013-01-17T18:32:30.000-0500"
resolved: "2010-04-06T18:31:05.000-0400"

---



{% raw %}



## Description

<div markdown="1" class="description">

In the h2lcperf test when BTM runs background recovery these warnings are sometimes reported:

2010-03-31 02:57:57,680 WARN [Recoverer] - <error running recovery on resource 'org.springframework.samples.petclinic.PetType@petClinic.cacheManager', resource marked as failed (background recoverer will retry recovery)>
java.lang.NullPointerException
	at org.terracotta.modules.ehcache.xa.XidClustered.<init>(XidClustered.java:17)
	at org.terracotta.modules.ehcache.xa.EhcacheXAStoreClusteredImpl.getPreparedContext(EhcacheXAStoreClusteredImpl.java:104)
	at net.sf.ehcache.transaction.xa.EhcacheXAResourceImpl.markContextForRollback(EhcacheXAResourceImpl.java:568)
	at net.sf.ehcache.transaction.xa.EhcacheXAResourceImpl.recover(EhcacheXAResourceImpl.java:283)
	at bitronix.tm.recovery.RecoveryHelper.recover(RecoveryHelper.java:74)
	at bitronix.tm.recovery.RecoveryHelper.recover(RecoveryHelper.java:39)
	at bitronix.tm.recovery.Recoverer.recover(Recoverer.java:205)
	at bitronix.tm.recovery.Recoverer.recoverAllResources(Recoverer.java:174)
	at bitronix.tm.recovery.Recoverer.run(Recoverer.java:113)
	at java.lang.Thread.run(Thread.java:619)
2010-03-31 02:57:57,703 INFO [Recoverer] - <recovery committed 0 dangling transaction(s) and rolled back 0 aborted transaction(s) on 9 resource(s) [org.springframework.samples.petclinic.Specialty@petClinic.cacheManager, org.springframework.samples.petclinic.Owner.petsInternal@petClinic.cacheManager, org.springframework.samples.petclinic.Visit@petClinic.cacheManager, org.springframework.samples.petclinic.Vet@petClinic.cacheManager, org.springframework.samples.petclinic.Pet@petClinic.cacheManager, org.springframework.samples.petclinic.Vet.specialtiesInternal@petClinic.cacheManager, org.springframework.samples.petclinic.Owner@petClinic.cacheManager, org.springframework.samples.petclinic.Pet.visitsInternal@petClinic.cacheManager, mysql] (restricted to serverId 'h2lcperf')>


2010-03-31 02:15:48,867 WARN [Recoverer] - <error running recovery on resource 'org.springframework.samples.petclinic.Owner@petClinic.cacheManager', resource marked as failed (background recoverer will retry recovery)>
java.lang.IllegalStateException: Context was marked as commited already!
	at org.terracotta.modules.ehcache.xa.PreparedContextClusteredImpl.\1\1tc\1wrapped\1setRolledBack(PreparedContextClusteredImpl.java:59)
	at org.terracotta.modules.ehcache.xa.PreparedContextClusteredImpl.setRolledBack(PreparedContextClusteredImpl.java)
	at net.sf.ehcache.transaction.xa.EhcacheXAResourceImpl.markContextForRollback(EhcacheXAResourceImpl.java:585)
	at net.sf.ehcache.transaction.xa.EhcacheXAResourceImpl.recover(EhcacheXAResourceImpl.java:283)
	at bitronix.tm.recovery.RecoveryHelper.recover(RecoveryHelper.java:74)
	at bitronix.tm.recovery.RecoveryHelper.recover(RecoveryHelper.java:39)
	at bitronix.tm.recovery.Recoverer.recover(Recoverer.java:205)
	at bitronix.tm.recovery.Recoverer.recoverAllResources(Recoverer.java:174)
	at bitronix.tm.recovery.Recoverer.run(Recoverer.java:113)
	at java.lang.Thread.run(Thread.java:619)
2010-03-31 02:15:48,870 INFO [Recoverer] - <recovery committed 0 dangling transaction(s) and rolled back 0 aborted transaction(s) on 9 resource(s) [org.springframework.samples.petclinic.Specialty@petClinic.cacheManager, org.springframework.samples.petclinic.PetType@petClinic.cacheManager, org.springframework.samples.petclinic.Owner.petsInternal@petClinic.cacheManager, org.springframework.samples.petclinic.Visit@petClinic.cacheManager, org.springframework.samples.petclinic.Vet@petClinic.cacheManager, org.springframework.samples.petclinic.Pet@petClinic.cacheManager, org.springframework.samples.petclinic.Vet.specialtiesInternal@petClinic.cacheManager, org.springframework.samples.petclinic.Pet.visitsInternal@petClinic.cacheManager, mysql] (restricted to serverId 'h2lcperf')>



This is because in EhcacheXAResourceImpl.recover() there is this snippet of code:

      for (Xid preparedXid : xids) {
          markContextForRollback(preparedXid);
      }

XAResource.recover() isn't supposed to do anything with in-doubt transactions but merely report them. It's up to the TM to act on them.

</div>

## Comments


{:.comment-heading}
### **Ludovic Orban** <span class="date">2010-04-01</span>

<div markdown="1" class="comment">

Fixed in trunk.

</div>


{:.comment-heading}
### **Ludovic Orban** <span class="date">2010-04-06</span>

<div markdown="1" class="comment">

This method call was there for a good reason, it was just poorly named

</div>


{:.comment-heading}
### **Ludovic Orban** <span class="date">2010-04-06</span>

<div markdown="1" class="comment">

 re-enabled method call in recover() + fixed related race conditions

</div>


{:.comment-heading}
### **Himadri Singh** <span class="date">2010-04-28</span>

<div markdown="1" class="comment">

Verified by running h2lcperf test in
Ehcache Core version 2.1.0-SNAPSHOT was built on 2010-04-27 11:37:49, at revision 2348, with jdk 1.6.0\115 

</div>



{% endraw %}
