---

title: "SelfPopulatingCache prints exceptions to System.err"
layout: issue
tags: 
permalink: /browse/EHC-738

issue_key: EHC-738
issue_numeric_sort_key: 738
issuetype: "Bug"
project: "Ehcache Core"
project_key: "EHC"
status: "Closed"
resolution: "Fixed"
priority: "2 Major"
components: "ehcache-core"
labels: 
assignee: "alexsnaps"
reporter: "edalquis"
votes:  0
watchers: 0

created: "2010-06-17T14:08:55.000-0400"
updated: "2010-07-15T17:14:52.000-0400"
resolved: "2010-06-20T19:07:51.000-0400"




---

{% raw %}

## Description

<div markdown="1" class="description">

At SelfPopulatingCache:85 there is "throwable.printStackTrace();"

It would be good if Ehcache wasn't writing to System.err when an exception occurs and leaves that to the client application.

</div>

## Comments


{:.comment-heading}
### **Steve Harris** <span class="date">2010-06-20</span>

<div markdown="1" class="comment">

This seems pretty easy to fix right alex?

</div>


{:.comment-heading}
### **Alexander Snaps** <span class="date">2010-06-20</span>

<div markdown="1" class="comment">

Just removed the printing, the exception was wrapped and re-thrown anyways

</div>



{% endraw %}
