---

title: "ArrayIndexOutOfBoundsException when assembling a clustered cache entry"
layout: issue
tags: 
permalink: /browse/EHC-993

issue_key: EHC-993
issue_numeric_sort_key: 993
issuetype: "Bug"
project: "Ehcache Core"
project_key: "EHC"
status: "Resolved"
resolution: "Cannot Reproduce"
priority: "2 Major"
components: ""
labels: 
assignee: "drb"
reporter: "bozho"
votes:  0
watchers: 2

created: "2013-02-06T10:55:02.000-0500"
updated: "2013-02-11T12:25:48.000-0500"
resolved: "2013-02-11T12:25:48.000-0500"

---



{% raw %}



## Description

<div markdown="1" class="description">

When there is @\*ToMany mapping with fetchType=LAZY, hibernate wraps the objects in a javassist proxy. 

When these entities are found in the graph of an entity that is placed in clustered terracotta 3.0.6 cache, an ArrayIndexOutOfBoundsException occurs at hibernate's TypeHelper.assemble(..)

It doesn't happen if the cache is not clustered.


</div>

## Comments


{:.comment-heading}
### **Bozhidar Bozhanov** <span class="date">2013-02-08</span>

<div markdown="1" class="comment">

The issue might be related to a different scenario. Ignore for now.

</div>


{:.comment-heading}
### **Fiona OShea** <span class="date">2013-02-11</span>

<div markdown="1" class="comment">

Closing as not reproducible unless we hear otherwise from reporter

</div>



{% endraw %}
