---

title: "CacheWriterConfiguration.notifyListenersOnException"
layout: issue
tags: 
permalink: /browse/EHC-814

issue_key: EHC-814
issue_numeric_sort_key: 814
issuetype: "Bug"
project: "Ehcache Core"
project_key: "EHC"
status: "Closed"
resolution: "Fixed"
priority: "2 Major"
components: "ehcache-core"
labels: 
assignee: ""
reporter: "alexsnaps"
votes:  0
watchers: 0

created: "2010-12-13T11:53:13.000-0500"
updated: "2012-07-27T19:59:35.000-0400"
resolved: "2011-02-11T20:46:03.000-0500"




---

{% raw %}

## Description

<div markdown="1" class="description">

When using replication and the writer feature, CacheWriterConfiguration.notifyListenersOnException should be turned on automatically if I am not mistaken.
Indeed, when the writer throws an exception, the element still has made it into the Store and hence should probably still be replicated to other nodes...
See net.sf.ehcache.Cache.putInternal

</div>

## Comments


{:.comment-heading}
### **Alexander Snaps** <span class="date">2011-01-21</span>

<div markdown="1" class="comment">

I think this is actually a documentation issue.
Given we replicate caches through the Listener API, there isn't much I can think of that could be done to make sure this flag is turned on.
I think we should add a note in the Writer doc to mention that, if you use replicated caches, you should probably turn the flag on to be sure all Store changes are replicated, whether the writer-through succeeded or not...

</div>


{:.comment-heading}
### **ilevy** <span class="date">2011-02-11</span>

<div markdown="1" class="comment">

added text to the bullet for notifyListenersOnException in write\_through\_caching.apt

</div>



{% endraw %}
