---

title: "Made the Multicast Heartbeat Sender More Robust"
layout: issue
tags: 
permalink: /browse/EHC-326

issue_key: EHC-326
issue_numeric_sort_key: 326
issuetype: "Bug"
project: "Ehcache Core"
project_key: "EHC"
status: "Closed"
resolution: "Fixed"
priority: ""
components: ""
labels: 
assignee: "drb"
reporter: "sourceforgetracker"
votes:  0
watchers: 0

created: "2009-09-21T15:08:04.000-0400"
updated: "2009-09-22T23:44:44.000-0400"
resolved: "2009-09-22T23:44:44.000-0400"




---

{% raw %}

## Description

<div markdown="1" class="description">

I found that if I caused an IO exception in the
heartbeat sender thread that it would throw out of the
run() method and thread would never restart.  This can
be reproduced by simply pulling the network cable out
of a machine for a few seconds and then replacing it. 
The cluster member then is in a state where it receives
cache updates but does not emanate them.

I resolved this by putting an outer while around the
socket.send() loop, trapping the exception inside it,
then allowing it to recycle the socket.  I also moved
the closeSocket() call into a finally block of the
outer try. 
Sourceforge Ticket ID: 1583996 - Opened By: tonyvoss - 24 Oct 2006 20:27 UTC

</div>

## Comments


{:.comment-heading}
### **Fiona OShea** <span class="date">2009-09-22</span>

<div markdown="1" class="comment">

Re-opening so that I can properly close out these issues and have correct Resolution status in Jira

</div>



{% endraw %}
